language: python

branches:
  only:
    - master

virtualenv:
  system_site_packages: true

python:
  - "2.7"

before_install:
  - "easy_install pip==1.4.1"
  - pip install flake8

install:
  - sudo apt-get -qq -y update
  - sudo apt-get install -y libgdal1h python-gdal
  - sudo apt-get install -y python-virtualenv python-imaging python-lxml python-pyproj python-shapely python-nose python-httplib2 python-httplib2 gettext
  - sudo apt-get install -y --force-yes openjdk-6-jdk ant maven2 libjai-imageio-core-java --no-install-recommends
  - pip install -e . --use-mirrors
  - pip install -e .[docs]
  - paver sync

script:
  - python manage.py test geoshape.core.tests
  - flake8 geoshape
  - cd docs && make html

after_script:
  - paver reset_hard

notifications:
  irc:
    channels:
      - "irc.freenode.org#rogue"